### ISSUE TITLE
Layers dont follow when export view

### ISSUE THREAD

**Issue by Abelon38** [3dcitydb/3dcitydb-web-map#10]
Hi there1

I have tried to create a map based on WMS and it works fine but when "Generate Scen Link" I see that the WMS dont follow up in the created link. 
Is this a problem or maybe I am missing something?
Regards!
Abel

**Comment by yaozhihang** [comment]
Hi Abel,

i can also reproduce the same issue. It seems that this is a bug of the web client. I'll try to fix it as soon as possible.

thanks and regards,

Zhihang

**Comment by Abelon38** [comment]
Hi Zhihang !

I found that not just the layes problem but also those configurations on basemap and terrain wont follow neither in the created link. 

Regards!
Abel

**Comment by yaozhihang** [comment]
This issue has been fixed in a41c9ed463685d4f0dd1dfd3d0a213d9eec9f7e5
