### ISSUE TITLE
Dropbox layers not loading?

### ISSUE THREAD

**Issue by Abelon38** [3dcitydb/3dcitydb-web-map#11]
Hi !

I am trying to load a glTF demo file from DropBox business on the web client. I dont get an error but the layer is not loading and the web client gets stack in loading but nothing happens..

This is the link: https://www.dropbox.com/s/v0qha9u6adt3cef/Sickla_nya.glb?dl=0

Any idea ?
Regards!
Abel

**Comment by yaozhihang** [comment]
you need to publish your glTF data via the Dropbox's **Public** folder.

**Comment by Abelon38** [comment]
Hi Zhihang!

I used the public folder and nothing happens. You can see how I am doing on
the picture.  This is the link I am using from my public Dropbox:
https://dl.dropboxusercontent.com/u/625263859/Sickla_nya.glb
[image: Infogad bild 1]

Regards,
Abel



2016-11-24 20:51 GMT+01:00 Zhihang Yao <notifications@github.com>:

**Comment by Abelon38** [comment]
Hi There!

I think maybe what is missing is a JSON file that should be appended to the .glb file, or? 

Regards!
Abel

**Comment by yaozhihang** [comment]
Hi Abel,

the current version of the 3D web client does not support reading and loading binary glTF files with .glb suffix, only ".gltf" is allowed. A workaround solution for that is adjusting the source code. see the following link:
https://github.com/3dcitydb/3dcitydb-web-map/blob/master/js/CitydbKmlDataSource.js#L1367
There you just need to replace the string ".gltf" by ".glb". Plesae try this.

best

Zhihang

**Comment by Abelon38** [comment]
Hi !

I created the .glb file with Cesium converter you find here:
http://cesiumjs.org/convertmodel.html  Then I load the resulting layer on
my public DropBox and I get this link:
https://dl.dropboxusercontent.com/u/625263859/Sickla_nya.glb

Then I insert the link  URL(*) under "Add/ Configure Layer " , I give the
Name of the layer.but nothing happens, just loading and loading..

Can you try the link your self? or is there a way to check if there is
something wrong with the modell?
Regards
Abel



2016-11-25 11:04 GMT+01:00 Zhihang Yao <notifications@github.com>:

**Comment by Abelon38** [comment]
Hi Zhihang!

I have even done the change you recomended on this link: https://github.com/3dcitydb/3dcitydb-web-map/blob/master/js/CitydbKmlDataSource.js#L1367 and still I am getting the same problem. I am guessing that this is a DropBox issue. I Will give a try to the 3Dcitydb and try the connection from there instead.

Thank you for your time!
Regards,
Abel

**Comment by yaozhihang** [comment]
Hi Abel,

the 3D web client cannot load an individual glTF model by entering its web link into the text field "URL(*)", where only the URL of the so-called "Master JSON file" can be entered. For more details please read carefully the 3DCityDB-Documentation-3.3 (Chapter 5.5 and Chapter 8.3.2). 

best

Zhihang

**Comment by Abelon38** [comment]
Thanks Zhihang!

Then I understand that the only way to create the. JSON file is while exporting it from the 3Dcitydb, or? I am having some trables when importing models in to the 3Dcitydb. Is that possible to import directly into the 3Dcitydb via FME. Are the information related good practices for creating and importing modells? 
Just now I am getting this error when importing a modell done in Sketchup and converted to CityGML with FME:   "Failed to resolve XLink reference '#fme-gen-fd78da5a-8ba3-44c5-8dee-ad2b2ed75483'.

Regards,
Abel

**Comment by Abelon38** [comment]
Hi Zhihang!

Thanks for your respond! Is there a free or comercial program to convert
KMZ/KML or Collada files to CityGML that can easylly be  imported with
3dCitydb Importer/Exporter? Alternativ 2: How can I get a working FME
workspace in ordet to archive this goal.

Thank your for time and have a greate weekend!

Abel Gonzalez

2016-11-30 22:38 GMT+01:00 Zhihang Yao <notifications@github.com>:

**Comment by yaozhihang** [comment]
Hi Abel,

as far as I know, there is no such software tool or FML workspace available allowing to convert KML/COLLADA  to CityGML directly. However, another possible way is to use the programming language JAVA to read and parse the KML file and write to CityGML file using the open source library [citygml4j](https://github.com/citygml4j/) 

best

Zhihang

**Comment by Abelon38** [comment]
Thanks Zhihang for your repply!

Is there a step by step on how to use the  citygml4j? I tried a bit with it but still, it is difficult to know where to start. 
I did installed  citygml4j, the next step would be to configurate so I can convert KMZ created with Sketchup to CityGML.

Thanks for your dedication.
Abel Gonzalez

**Comment by clausnagel** [comment]
Abel, I have been following this thread for a while. At my company [virtualcitySYSTEMS](http://www.virtualcitysystems.de/en/) it is part of our daily business to create CityGML from input data including KML/KMZ files. And we use FME most of the time. We also offer FME trainings for this purpose. If you are interested, do not hesitate to contact me per email. 

Cheers,
Claus

**Comment by Abelon38** [comment]
Hi Claus!
I hope your are doing great! Can you contact me via mail to: abel@mundogis.se
Regards,
Abel

**Comment by Son-HNguyen** [comment]
Closed. Feel free to reopen if you still have issues.
