### ISSUE TITLE
texture or not?

### ISSUE THREAD

**Issue by ClementD** [3dcitydb/3dcitydb-web-map#12]
Hi,

I am a new user of 3d City DB, an happy one you can trust me.

I have a little question about objects wich can be loaded in 3D city wen map.
I have make several tries to load objects created with import / export tool, but i can not see them in my browser.
I have no problem with extruded object, but only with collada / glTF (appearance = Rhino texturing)

Is it possible to load this kind of object in 3D city db wep map, or in cesium more generaly?

Thanks.

Clement

**Comment by yaozhihang** [comment]
Hi Clement,

the 3d-web-map is capable of visualizing textured glTF models exported using the import/export tool. 
Via the following link you can find a hands-on tutorial document which is a very helpful learning material for 3DCityDB beginners and will guide you step by step through how to use the 3DCityDB software suite for setting up a 3D web application:
http://www.gis.bgu.tum.de/fileadmin/w00bov/www/Dokumente/Projekte/3DCityDB/3DCityDB_V3.3_Hands-On_Tutorial.pdf

best,

Zhihang

**Comment by ClementD** [comment]
Thank you very much, I will try it right now.

Best regards.

Clément
