### ISSUE TITLE
b3dmBerlinExample,An error occurred while rendering. Rendering has stopped

### ISSUE THREAD

**Issue by litterbug23** [3dcitydb/3dcitydb-web-map#13]
TypeError: invalid 'instanceof' operand Cesium.Batched3DModel3DTileContent B3DMLayer.prototype.addToCesium/<@http://localhost/js/b3dmlayer.js:241:1 r.prototype.raiseEvent@http://localhost/ThirdParty/Cesium-1-14-3dtiles/Cesium.js:443:22693 P@http://localhost/ThirdParty/Cesium-1-14-3dtiles/Cesium.js:481:11475 R.prototype.update@http://localhost/ThirdParty/Cesium-1-14-3dtiles/Cesium.js:481:14156 a.prototype.update@http://localhost/ThirdParty/Cesium-1-14-3dtiles/Cesium.js:487:8191 xt@http://localhost/ThirdParty/Cesium-1-14-3dtiles/Cesium.js:489:6409 Pt@http://localhost/ThirdParty/Cesium-1-14-3dtiles/Cesium.js:489:7156 Rt.prototype.render@http://localhost/ThirdParty/Cesium-1-14-3dtiles/Cesium.js:489:13629 A.prototype.render@http://localhost/ThirdParty/Cesium-1-14-3dtiles/Cesium.js:494:23477 t@http://localhost/ThirdParty/Cesium-1-14-3dtiles/Cesium.js:494:10456

**Comment by yaozhihang** [comment]
You may check the following example where the building objects are streamed using Cesium 3D-Tiles
https://github.com/3dcitydb/3dcitydb-web-map/tree/master/examples/kmlManhattanExample

**Comment by chenfeiyang2009** [comment]
I met the same problem,how to solve this problem? please  help ,thanks!

**TypeError: invalid 'instanceof' operand Cesium.Batched3DModel3DTileContent**

**Comment by yaozhihang** [comment]
The class `b3dmlayer.js` is superseded by the class `Cesium3DTilesDataLayer.js`. 
So, please use `Cesium3DTilesDataLayer.js` to load your 3D Tiles datasets into the 3dcitydb-web-map. 
Examples on how to use this class can be found via the following link
https://github.com/3dcitydb/3dcitydb-web-map/blob/master/examples/kmlManhattanExample/index.html

**Comment by nytschgeusen** [comment]
@yaozhihang: It would be great if you could adapt the example https://github.com/3dcitydb/3dcitydb-web-map/tree/master/examples/b3dmBerlinExample to the new Cesium class `Cesium3DTilesDataLayer.js` because it is one of the three demos of the 3dcitydb-web-map client (yesterday I tested the 3dcitydb-web-map client with Firefox and Chrome and I obtained the same failure message as described above).

**Comment by Son-HNguyen** [comment]
Closed due to inactivity.
