### ISSUE TITLE
visualize a local file

### ISSUE THREAD

**Issue by balazsdukai** [3dcitydb/3dcitydb-web-map#15]
I've been reading through the documentation and it seems to me that the only way to visualize a city model is to upload the spreadsheet/kml/etc. export to a remote server (i.e. Dropbox). Is that correct or I'm missing some info?

**Comment by thomashkolbe** [comment]
You are right; the model data needs to be served by
a web server using the http or https protocol. However,
a locally stored KML/glTF export can be visualized on
the same computer by running a local web server.

Best regards
Thomas Kolbe


Am 20.02.17 um 14:28 schrieb Balázs Dukai:
