### ISSUE TITLE
How to delete, edit and save an objekt?

### ISSUE THREAD

**Issue by Abelon38** [3dcitydb/3dcitydb-web-map#16]
Hi ! 

First of all thank you for this great product! I am using 3DcityDB and still learning a lot! 

I wonder how to delete, edit or uppdate an objekt. The Impoter/exporter does´nt show this possibilities.. 

Is there a tool for editing objects on the fly ? Im am using CityEditor and is great, but still you have to export from 3DcityDB--- import in SketchUp-- edit-export and finally import to the 3DcityDB and then this does´n replace the existing object..  

Regards
Abel

**Comment by FxKu** [comment]
Hi Abel,
during my time at virtualcitySYSTEMS I've created plugins for the Importer/Exporter to satisfy these tasks - integrating objects back into the database (e.g. coming from a sketch-up process) and delete objects based on some filter criteria. These are commercial extensions. If you are interested, talk to my former collegues.
Live editing of 3DCityDB features would require a GIS with 3D capabilities and probably additional views on the data. As far as I know Bentley has a solution for this. Not sure about Oracle.
Cheers,
Felix

**Comment by Son-HNguyen** [comment]
Closed. Feel free to reopen if you still have any issues.

**Comment by Son-HNguyen** [comment]
Reopened for future consideration.
