### ISSUE TITLE
cannot start the 3dcitydb-web-map

### ISSUE THREAD

**Issue by hualunchang** [3dcitydb/3dcitydb-web-map#17]
i install nodejs and follow the  tutorial to start the 3dcitydb-web-map. the console print the result "Cesium development server running publicly. Connect to localhost:8000/" 
but when i enter the url "http://localhost:8000/3dcitydb-web-map/3dwebclient/index.html"
the chrome show "Cannot GET /3dcitydb-web-map/3dwebclient/index.html"

**Comment by yaozhihang** [comment]
Try the url "http://localhost:8000/3dwebclient/index.html"

**Comment by Son-HNguyen** [comment]
Closing this thread. Please feel free to reopen if you have further questions.
