### ISSUE TITLE
how to show single gltf on the client

### ISSUE THREAD

**Issue by hualunchang** [3dcitydb/3dcitydb-web-map#18]
i have exported only a single building from the 3d city db, and it create a kml file and a folder include dae and gltf. i add a layer which url is the kml's path ,but it seems not success .how can i add a single gltf on the  client

**Comment by yaozhihang** [comment]
Try the following steps:
1. Use the BoundingBox-filter to select a very small bounding box surround your desired building object
2. Choose the Tiling option "No Tiling"
3. After the exprots, a "Master" json file will be created which can be used for loading the exported glTF object into the 3dcitydb-web-map

**Comment by Son-HNguyen** [comment]
Closed. Feel free to reopen if you still have any issues.
