### ISSUE TITLE
What’s the difference or relationship between web-client-map and 3d-tile branch of cesium?

### ISSUE THREAD

**Issue by salutonalpha** [3dcitydb/3dcitydb-web-map#19]
I find this two projects both use tilesets as input data to render. The first uses kmz and the second uses i3dm or b3dm. Is it the extension to cesium-3dtile?

**Comment by yaozhihang** [comment]
No, the tiled KML/KMZ models exported from the 3DCityDB are organized using our own specific tiling schema which was developed two and a half years ago (before the Cesium's 3DTiles came up). This tiling schema is grid-based and has a quite simple schema structure compared to the Cesium's 3DTiles. More details can be found in the [3DCityDB documentation](https://github.com/3dcitydb/3dcitydb/tree/master/Documentation) in the pages 137-141. The 3dcitydb-web-map is an extension of the Cesium viewer and is able to dynamically load and unload the KML/KMZ data tiles based on the tiling schema.

**Comment by salutonalpha** [comment]
Thanks a lot.
