### ISSUE TITLE
Elevation

### ISSUE THREAD

**Issue by strech345** [3dcitydb/3dcitydb-web-map#2]
Hello,

if i insert a elevation Model, the building tiles are move at perspective change. Do someone know what is the Problem?
I've change the elevation parameters at export but it doesnt solve the problem.

see screenshots
[https://pl.vc/5rtkr](url)
[https://pl.vc/1p0q1](url)

```
        var terrainProvider = new Cesium.CesiumTerrainProvider({
            url: '//assets.agi.com/stk-terrain/world',
            requestVertexNormals: true
        });

        Cesium.BingMapsApi.defaultKey = 'ApOW9LMkerqWIVSnFauilSeaZyp8df66byy1USCTjgTdMvhb4y1iAhEsUHQfCgzq';
        this.viewer = new Cesium.Viewer('cesiumContainer', {
            baseLayerPicker: false,
            animation: false,
            timeline: false,
            infoBox: false,
            scene3DOnly: true,
            navigationHelpButton: false,
            fullscreenButton: false,
            terrainProvider: terrainProvider
        });

        var extent = new Cesium.Rectangle.fromDegrees(this.VIEWBOUNDARY[0],this.VIEWBOUNDARY[1],this.VIEWBOUNDARY[2],this.VIEWBOUNDARY[3]);
        this.viewer.camera.setView({ destination: extent });
        Cesium.Camera.DEFAULT_VIEW_RECTANGLE = extent;
        Cesium.Camera.DEFAULT_VIEW_FACTOR = 0;
        this.webMap = new WebMap3DCityDB(this.viewer);
        this.webMap.activateViewChangedEvent(true);
        this.webMap.activateMouseClickEvents(true);

this.webMap.addLayer({'url': '../overlays/charlottenburg-ext-kmz-800/cb_extruded.json'})
```

**Comment by yaozhihang** [comment]
Hi,

could you please check your screenshot-links? I can't access your screenshots via the links.

regards,

Zhihang

**Comment by strech345** [comment]
copy the link to the url works ;-)

**Comment by yaozhihang** [comment]
Hi,

the terrain data you use is the globe terrain model of STK which has a relatively low resolution (30m in Europe). That may cause the problem displayed in the first screenshot. 

zhihang

**Comment by strech345** [comment]
but not 30m in height ;-)

**Comment by strech345** [comment]
Hello yaozhihang
sorry, you are right. But it's not the resolution, it have a wrong datum
http://gis.stackexchange.com/questions/152886/cesium-terrain-tiles-too-high-by-roughly-30m
It is 30m to high. I saw it in Berlin, Buidlings would be shown if i add 30-40m to the grundheight.
