### ISSUE TITLE
Adding gltf, CZML 

### ISSUE THREAD

**Issue by Abelon38** [3dcitydb/3dcitydb-web-map#21]
Hi!

I hope your are doing great!
I am trying to add ordinary cesium layers such as GLTF and CZML on same way I use to do on Cesium as soon as I put a code inside skript.js the whole map keep loading.. May be a there is another way? This a working layer on Cesium:

var scene = viewer.scene;

var modelMatrix = Cesium.Transforms.eastNorthUpToFixedFrame(
    Cesium.Cartesian3.fromDegrees(14.55677,61.02010, 187));
var model = scene.primitives.add(Cesium.Model.fromGltf({
	url : 'data/mora/mora_bygg.gltf',
    modelMatrix : modelMatrix,
    scale : 1.0,
    castShadows: false,
    receiveShadows: false,
    heightReference: Cesium.HeightReference.CLAMP_TO_GROUND,
    scene: scene
})); 

Regards?
Abel Gonzalez

**Comment by Son-HNguyen** [comment]
Similar to WMS (see comments https://github.com/3dcitydb/3dcitydb-web-map/issues/22#issuecomment-381623329 and https://github.com/3dcitydb/3dcitydb-web-map/issues/22#issuecomment-383524380), you can manually add your own e.g. building layer using the function `addNewLayer()` starting from [line 881](https://github.com/3dcitydb/3dcitydb-web-map/blob/master/3dwebclient/script.js#L881) in the main script file. Note that you have to initialize the variable `addLayerViewModel` correspondingly. 

If the layer keeps loading without showing the results, make sure both the web client has access to the visualization files (for example by hosting them on the same domain). See more at #9, #26, #31 and #39.
