### ISSUE TITLE
WMS problem when sharing

### ISSUE THREAD

**Issue by Abelon38** [3dcitydb/3dcitydb-web-map#22]
Hi!

It seams that 3DcityDB webmap wont include all WMS I added when sharing the map. Only one of my WMS is condired. Is there a way to fix this issue? 

Thanks for your time!

Regards, Abel

**Comment by Son-HNguyen** [comment]
Hi Abel,

could you provide us the link of your client including all WMS you wished to include?

Best,
Son

**Comment by Abelon38** [comment]
Hi Son!

Ypu can see my work here: https://3d.sokigo.com/demo/ This is a combination between Cesium 1.43 and 3dCityDB web client. I can do many staffs such as drag and drop, etc. 
This is a link tom my WMS: https://3d.sokigo.com/geoserver/ows
and the layers are : pbr_bestammelser   and   pbr_detaljplaner

Because my changes I am facing som  problem with sharing. Is like an empty extra terrain layer is created when charing the map...

Any help will be appreciated !

Best regars
Abel

**Comment by Son-HNguyen** [comment]
Hi Abel,

it appears that the WMS link you provided is empty or invalid. I guess you meant these two layers: 
[bakgrunder:pbr_bestammelser](https://3d.sokigo.com/geoserver/bakgrunder/wms?service=WMS&version=1.1.0&request=GetMap&layers=bakgrunder:pbr_bestammelser&styles=&bbox=34124.63216192637,5946605.963506611,1087720.4741152613,8046807.538237412&width=385&height=768&srs=EPSG:3006&format=image%2Fjpeg) and [bakgrunder:pbr_detaljplaner](https://3d.sokigo.com/geoserver/bakgrunder/wms?service=WMS&version=1.1.0&request=GetMap&layers=bakgrunder:pbr_detaljplaner&styles=&bbox=34124.63216192637,5946605.963506611,1087720.4741152613,8046807.538237412&width=385&height=768&srs=EPSG:3006&format=image%2Fjpeg) (this one is just blank).

However, when I entered these URLs into your client as a WMS layer, an error ```404``` (file or directory not found) is returned. Removing the ```/proxy/``` parameter seems to get rid of this error as a workaround. But since I do not know in details the modifications you've made to your web client, please test again if this is what you wanted to achieve.

Cheers,
Son

**Comment by Abelon38** [comment]
Hi Son! 

Thanks for your answer  and time. I used to remove the "proxy" and the layers works, But the problem continues. Here are tow working WMS:
https://3d.sokigo.com/geoserver/bakgrunder/wms      
Layer:     pbr_bestammelser 

and   https://3d.sokigo.com/geoserver/oversvamning/wms      
layer      oversv_stock

These  WMS works and you kan see tha they get in ito the ImageryLayers box, but only one of them will be visible. I have even tried with your demo site : https://3dcitydb.org/3dcitydb-web-map/1.4/3dwebclient/index.html and is the same problem.

Thanks for your time!
Abel

**Comment by Son-HNguyen** [comment]
Hi Abel,

the current version only displays one imagery layer at a time, which means that it currently does not support displaying two WMS layers on the globe simultaneously or adding more than one custom WMS layers to the base layer picker. However, if you indeed want to add two fixed WMS layers to the base layer picker, you could manually insert them into the code to fit to your specific use case, please refer to the function [addWebMapServiceProvider()](https://github.com/3dcitydb/3dcitydb-web-map/blob/master/3dwebclient/script.js#L828). I hope this answers your question.

Best,
Son

**Comment by Abelon38** [comment]
Hi Son!

I will give it a try and I will return to you.

Thanks for your time!

Regards!
Abel

2018-04-13 12:19 GMT+02:00 Son H. Nguyen <notifications@github.com>:

**Comment by Abelon38** [comment]
Hi Son! I just added this code with my WMS link and dint work att all. any idea on how to add 2 or 3 fixed WMS on the LayersPicker box? 

function addWebMapServiceProvider() {
    var baseLayerPickerViewModel = viewer.baseLayerPicker.viewModel;
    var wmsProviderViewModel = new Cesium.ProviderViewModel({
        name: addWmsViewModel.name.trim("orto"),
        iconUrl: addWmsViewModel.iconUrl.trim("Widgets/Images/ImageryProviders/bingAerial.png"),
        tooltip: addWmsViewModel.tooltip.trim("testing"),
        creationFunction: function () {
            return new Cesium.WebMapServiceImageryProvider({
                url: addWmsViewModel.url.trim("https://3d.sokigo.com/geoserver/bakgrunder/wms"),
                layers: addWmsViewModel.layers.trim("orto"),
                parameters: Cesium.queryToObject(addWmsViewModel.additionalParameters.trim()),
                proxy: addWmsViewModel.proxyUrl.trim().length == 0 ? null: new Cesium.DefaultProxy(addWmsViewModel.proxyUrl.trim())
            });
        }
    });
    baseLayerPickerViewModel.imageryProviderViewModels.push(wmsProviderViewModel);
    baseLayerPickerViewModel.selectedImagery = wmsProviderViewModel;
}


Best regards!
Abel

**Comment by Son-HNguyen** [comment]
Hi Abel,

you can manually add two layers using this code:

```JavaScript
addWebMapServiceProviderManual();
function addWebMapServiceProviderManual() {
    var baseLayerPickerViewModel = cesiumViewer.baseLayerPicker.viewModel;
    
    var addWmsViewModel1 = {
        name: 'Layer 1',
        iconUrl: '',
        tooltip: '',
        url: 'https://3d.sokigo.com/geoserver/bakgrunder/wms',
        layers: 'pbr_bestammelser',
        additionalParameters: '',
        proxyUrl: '/proxy/'
    };
    var wmsProviderViewModel1 = new Cesium.ProviderViewModel({
        name: addWmsViewModel1.name.trim(),
        iconUrl: addWmsViewModel1.iconUrl.trim(),
        tooltip: addWmsViewModel1.tooltip.trim(),
        creationFunction: function () {
            return new Cesium.WebMapServiceImageryProvider({
                url: addWmsViewModel1.url.trim(),
                layers: addWmsViewModel1.layers.trim(),
                parameters: Cesium.queryToObject(addWmsViewModel1.additionalParameters.trim()),
                proxy: addWmsViewModel1.proxyUrl.trim().length == 0 ? null: new Cesium.DefaultProxy(addWmsViewModel1.proxyUrl.trim())
            });
        }
    });
    baseLayerPickerViewModel.imageryProviderViewModels.push(wmsProviderViewModel1);
    // baseLayerPickerViewModel.selectedImagery = wmsProviderViewModel1;
    
    var addWmsViewModel2 = {
        name: 'Layer 2',
        iconUrl: '',
        tooltip: '',
        url: '',
        layers: 'https://3d.sokigo.com/geoserver/oversvamning/wms',
        additionalParameters: 'oversv_stock',
        proxyUrl: '/proxy/'
    };
    var wmsProviderViewModel2 = new Cesium.ProviderViewModel({
        name: addWmsViewModel2.name.trim(),
        iconUrl: addWmsViewModel2.iconUrl.trim(),
        tooltip: addWmsViewModel2.tooltip.trim(),
        creationFunction: function () {
            return new Cesium.WebMapServiceImageryProvider({
                url: addWmsViewModel2.url.trim(),
                layers: addWmsViewModel2.layers.trim(),
                parameters: Cesium.queryToObject(addWmsViewModel2.additionalParameters.trim()),
                proxy: addWmsViewModel2.proxyUrl.trim().length == 0 ? null: new Cesium.DefaultProxy(addWmsViewModel2.proxyUrl.trim())
            });
        }
    });
    baseLayerPickerViewModel.imageryProviderViewModels.push(wmsProviderViewModel2);
    baseLayerPickerViewModel.selectedImagery = wmsProviderViewModel2;
}
```

**Comment by Abelon38** [comment]
Thanks a lot Son! I will try it right away!

Regards,
Abel

**Comment by Abelon38** [comment]
Hi Son!

I just implemented your suggestion and it worked pefectly! Thanks a lot for your support! Here is my site: https://3d.sokigo.com/demo

I am trying to do the same with the 3DcityDB layer and I cant get the same result. I want my lod1-data to be on from start in the default webmap. Is that possible? This is my code:

addLayerViewModelManual();
function addLayerViewModelManual() {
	var addLayerViewModel1 = {
    url: "https://3d.sokigo.com/demo/data/lods/stock_collada_MasterJSON.json",
    name: "stock",
    thematicDataUrl: "",
    cityobjectsJsonUrl: "",
    minLodPixels: "",
    maxLodPixels: "",
    maxSizeOfCachedTiles: 200,
    maxCountOfVisibleTiles: 400
	}
  },
Cesium.knockout.track(addLayerViewModel1);
Cesium.knockout.applyBindings(addLayerViewModel1, document.getElementById('citydb_addlayerpanel'));

Regards!
Abel

**Comment by Son-HNguyen** [comment]
Hi Abel,

to insert e.g. a building layer you can either adjust the URL parameters (such as `?layer_0=...&name=...`) or use some codes as you were trying to in the previous comment. Here is an example code you can use:

```bash
addLOD1Manual();
function addLOD1Manual() {
    addLayerViewModel = {
        url: "https://3d.sokigo.com/demo/data/lods/stock_collada_MasterJSON.json",
        name: "stock",
        thematicDataUrl: "",
        cityobjectsJsonUrl: "",
        minLodPixels: "",
        maxLodPixels: "",
        maxSizeOfCachedTiles: 200,
        maxCountOfVisibleTiles: 400
    }
    addNewLayer();
}
```

The function `addLOD1Manual()` is our own specified function, which overrides the already defined `addLayerViewModel` object with new information and then calls the existing function [`addNewLayer()`](https://github.com/3dcitydb/3dcitydb-web-map/blob/master/3dwebclient/script.js#L789).

**Comment by Abelon38** [comment]
Thanks a lot Son!

Regards!
Abel

2018-04-23 12:10 GMT+02:00 Son H. Nguyen <notifications@github.com>:

**Comment by Abelon38** [comment]
Hi Son!

I hope you are doing great!

I am trying to add TerrainProvider från Cesium ion and tried the following
but is not working att all. any idea?

var addTerrainProviderModel1 = {
        name: 'Min terrain',
        iconUrl: 'img/orto.png',
        tooltip: '',
        url: 'Cesium.IonResource.fromAssetId(4537)',
        proxyUrl: ''
    };
    var terrainProviderModel1 = new Cesium.ProviderModel({
        name: addTerrainModel1.name.trim(),
        iconUrl: addTerrainModel1.iconUrl.trim(),
        tooltip: addTerrainViewModel1.tooltip.trim(),
        creationFunction: function () {
            return new Cesium.WebMapServiceImageryProvider({
                url: addTerrainViewModel1.url.trim(),
                layers: addTerrainViewModel1.layers.trim(),
                parameters:
Cesium.queryToObject(addTerrainViewModel1.additionalParameters.trim()),
                proxy: addTerrainViewModel1.proxyUrl.trim().length == 0 ?
null: new Cesium.DefaultProxy(addTerrainViewModel1.proxyUrl.trim())
            });
        }
    });
baseLayerPickerViewModel.terrainProviderViewModels.push(demProviderViewModel1);
    baseLayerPickerViewModel.selectedTerrain = demProviderViewModel1;

Best regards,
Abel Gonzalez


2018-04-23 14:18 GMT+02:00 Son H. Nguyen <notifications@github.com>:
