### ISSUE TITLE
webpack Support

### ISSUE THREAD

**Issue by Tugark** [3dcitydb/3dcitydb-web-map#24]
Hi there

I am using your full stack to generate our webmaps, starting from our citygml Files via your database solution up to the webclient.

Regarding the webclient, I am wondering whether you have any plans on making it webpack capable?

I do have a somewhat unstable beta version that uses webpack and builds a nice application (using all the node magic and node Cesium); however, it also needed some tweaks and some hacks to get it going. One particular hack I just had to make involved changing the CitydbUtils.js to not export a global variable, but rather the 'module.exports = {}' way.

However, before I invest a lot of work, I'd like to know whether you're planning to do this as well and if so, how we could collaborate on this.

On another note - thank you so much for all the work you've put into this. You're really doing a great job with the web map and I enjoy using your tools.

Best regards,

Lukas

**Comment by yaozhihang** [comment]
Hi Lukas,

thank you very much for sharing with us your successful experience in using our 3DCityDB software suite. 

We are not currenlty planning to build the 3dcitydb-web-map using Webpack. So it is very nice to hear that you are interested in working on this topic as Webpack is a realy nice tool which may make the organization of our 3dcitydb-web-map code much more modular. Please let us know if you have any further progress in this work.  

best regards

Zhihang
