### ISSUE TITLE
Update to  current Cesium Version

### ISSUE THREAD

**Issue by Tugark** [3dcitydb/3dcitydb-web-map#27]
Hi there

I've seen that you've got a branch that suggests you're updating to Cesium 1.41. However, the current version is 1.44 and I think we'd benefit from updating to the most recent sources (also bearing in mind the changes they're adding to e.g. the STK Terrain, which now leads to Cesium ION). I've updated the 3dcitydbwebmap to Cesium 1.44 in my fork which you can find here: https://github.com/Tugark/3dcitydb-web-map/tree/update-cesium

The main changes are the loadJson, loadBlob, loadXml which have been removed (they've been deprecated for long, and now they are removed). These kinds of requests are now handled by Cesium.Resource. No big fixes, but needs to be done nonetheless :-)

It does work, however, I did not open a pullrequest because of 4 reasons:
1. I don't know if you're accepting pull requests at all
2. I could not test everything, however I have not noticed any issues so far
3. I am not sure if there are more deprecated functions within the CityDB Client, but so far, I did not encounter any issues.
4. Unfortunately, my editor uses a syntax "cleaner", which leads to quite a messy commit, since it did not only update all the required changes, but also removed unneccessary new lines or whitespaces.

If you'd like to update to 1.44, I could create another branch without the syntax cleaner, so a pull request would be cleaner.

Best,
Lukas

**Comment by Tugark** [comment]
See PR #28

**Comment by Son-HNguyen** [comment]
Branch [update-cesium-1.44](https://github.com/3dcitydb/3dcitydb-web-map/tree/update-cesium-1.44) merged to [master](https://github.com/3dcitydb/3dcitydb-web-map).
