### ISSUE TITLE
Wrong Calculation of visible Tiles

### ISSUE THREAD

**Issue by strech345** [3dcitydb/3dcitydb-web-map#3]
Hey,

if i zoom to buildings, the tiles will be unload. I think the calculation of the  wgs84ToWindowCoordinates in CitydbKmlTilingManager is wrong. 
i saw it in charlottenburg, where i've 800 Tiles. If i zoom to one building, this tile, which have several buildings is gone. maxLodPixels is unessasry (i set it to -1 or 100000).
next example la goule (schweiz) with one tile: 

networklinkItem.lowerLeftCorner = 
x: 4309415.609526696
y: 525468.2715535653
z: 4656961.495218058
are this meters?

pixelCoveringSize is 0

bbox of this tile should be
6.95203757241971, 47.14848812644286, 7.14881825627412, 47.25313192874594

i use a older version of web map (which use cesium 1.16) because i've more of these problemes in the new versions (which use ccesium 1.18)

here is a screenshot
http://fs5.directupload.net/images/160229/7h3buyrr.png

**Comment by yaozhihang** [comment]
Could you send me a scene link of your web client displaying the "charlottenburg" data?
my email address: zhihang.yao@tum.de

**Comment by strech345** [comment]
its not poblic, may i could upload it to some hoster.

could it be a problem of reseze the screen?
because i dynamically resize the div
$("#cesiumContainer").css('height', Math.max($(window).height() - headerHeight, min_map_height) + 'px');

**Comment by yaozhihang** [comment]
Hi, 

I've tried to change the <div> tag size dynamically in JQuery using your pasted code. But I can still not reproduce the issue.

I think the best way to solve the problem is to send me the link of your web client or its source code via email.
