### ISSUE TITLE
Permanent layer in 3D web client?

### ISSUE THREAD

**Issue by fadelkoto** [3dcitydb/3dcitydb-web-map#30]
Hello. 
I have succesfully added my 3D building model layer to the web client. However, when I reload the web page, the layer added was gone. I am wondering can I make the layer attcach permanently in my 3D web client that everytime I open my web page the layer is still there? 
Thank You.

**Comment by fadelkoto** [comment]
Okay thank You @Son-HNguyen it works

**Comment by Son-HNguyen** [comment]
Glad it helped.
