### ISSUE TITLE
Problems with 3D-Web-Client and LOD3

### ISSUE THREAD

**Issue by gesa111** [3dcitydb/3dcitydb-web-map#36]
Hey,
I have CityGML LOD3 data, imported into the 3DCityDB. 
I used the KML/Collada/glTF Export to export my buildings as Collada/glTF in LOD3 (without generating a glTF Modell).
The generated kml-file can be displayed in Google Earth perfectly fine, but when I load the MasterJSON in 3DCityDB-Wep-Map-Client, it only shows a blue box on the ground and no buildings.
I tried the same with LOD2 buildings and it worked with the Wep-Map-Client.
Does anyone know what I did wrong? The CityGML files are valid. I also modified the Alttitude/Terrain settings in the Preferences but it's still not working.
Thanks in advance for any help

**Comment by FxKu** [comment]
#31

**Comment by FxKu** [comment]
Sounds similar to #31

**Comment by Son-HNguyen** [comment]
Closed. Feel free to reopen if the referenced issue did not solve your problem.
