### ISSUE TITLE
No allowed resource Access Control Allow Origin

### ISSUE THREAD

**Issue by stefanodecillis** [3dcitydb/3dcitydb-web-map#39]
Hi,

i'm trying to import a json file in "add/Configure Layer" but it gave me "no Access-Control-Allow-Origin head is present on the requested resource". 
This file was uploaded on Google Drive, Dropbox and GitHub even. It gave me the same error and i'm about to give up. 
Someone had the same problem?

**Comment by BWibo** [comment]
This issue seems to be realated to [CORS](https://de.wikipedia.org/wiki/Cross-Origin_Resource_Sharing).
Check this page [https://enable-cors.org/](https://enable-cors.org/) to enable CORS for your server.

**Comment by BWibo** [comment]
Issue #26 contains some discussion regarding this topic as well.

**Comment by stefanodecillis** [comment]
Yeah, the solution for me was to enable CORS on my server and client  and use resources within the project.
