### ISSUE TITLE
3D web client NY City buildings rotated by 90 Degrees

### ISSUE THREAD

**Issue by wisdomware** [3dcitydb/3dcitydb-web-map#41]
First, thanks to everyone who has contributed their work to this wonderful application.

Secondly, I successfully set up the 3D web client to run on my MacOS localhost:8000/. However, when I load the sample NYC building model, all of them were rotated by 90 degrees. I follow the readme.md but could not find what I did wrong. Can anyone help? 

![NYC_BuildingRotated90Degree](https://user-images.githubusercontent.com/25489391/54496712-face6480-48c8-11e9-8aff-6c9093d7eecb.png)

**Comment by thomashkolbe** [comment]
Hi, thanks for your kind words on the 3DCityDB application!

This looks like a mismatch of the glTF version used for the 3D model export and the version chosen for the layer within the 3D webmap client. In the viewer one can see from your screenshot that you have chosen version 2.0; I assume that for the glTF export you have chosen to use glTF version 1.0. The problem should easily resolve by simply chosing glTF version 1.0 in the viewer (and clicking on "Save layer settings"). Alternatively, you could do another export and configure the KML/COLLADA/glTF exporter to generate glTF version 2.0 instead.
