### ISSUE TITLE
unable to view textures of buildings

### ISSUE THREAD

**Issue by synpc** [3dcitydb/3dcitydb-web-map#42]
hi 
exported using 3dcitydb importer-exporter successfully(?);
kml renders correctly in google earth pro - building textures display correctly;
collada glTF exports - files seem to be exported correctly (during export process, dialog popup indicates texture images being exported), however, in web client, only geometry export displays (wireframes) when added as layer; when export collada with texture, buildings display as blacked-out boxes;
apprec any pointers
TIA
synpc

export:
![Capture_xp](https://user-images.githubusercontent.com/48705554/54902340-17dfe480-4f14-11e9-92c1-a0a42fd066bd.JPG)

google earth:
![Capture_ge](https://user-images.githubusercontent.com/48705554/54902300-f2eb7180-4f13-11e9-9024-df3922131382.JPG)

webclient collada:
![Capture_col](https://user-images.githubusercontent.com/48705554/54902464-786f2180-4f14-11e9-8d5a-871ad7405f17.JPG)

**Comment by Son-HNguyen** [comment]
I assume this is is glTF 2.0 right? Make sure you check the "Generate surface normals" in the Preferences -> KML/COLLADA/glTF Export -> Rendering -> Building in the Importer/Exporter.

**Comment by synpc** [comment]
hi
apprec prompt :)

yes, is gltf 2.0;
further clarification pls: am exporting textured model (db imported with imaged textures), hence unchecked this preference - will this make difference?

sample exported folder with image
![Capture_tx](https://user-images.githubusercontent.com/48705554/54908806-a871f100-4f23-11e9-95f0-0fbf8f423a7b.JPG)

thnx again

**Comment by Son-HNguyen** [comment]
Please first try to enable the surface normals (see picture) and check if the problem has been solved:

![image](https://user-images.githubusercontent.com/5765503/54910564-e0aa0d00-4eec-11e9-81cb-8a880877e199.png)

**Comment by synpc** [comment]
hi
thanks for prompt;
unfortunately, exporting collada with surface normals does not render textures as required

pref:
![CapturePref](https://user-images.githubusercontent.com/48705554/54969408-f84ec780-4fb8-11e9-84f0-6fed06075b10.JPG)

geometry only:
![Capture3g](https://user-images.githubusercontent.com/48705554/54969239-61820b00-4fb8-11e9-8513-3593a6a45917.JPG)

collada with surface:
![Capture3ksurface](https://user-images.githubusercontent.com/48705554/54969248-69da4600-4fb8-11e9-9a9b-86676171f80b.JPG)

apprec pointers to how to get textured display in webclient, similar to google earth:
![CaptureGooG](https://user-images.githubusercontent.com/48705554/54969370-c5a4cf00-4fb8-11e9-9b46-351ba7946041.JPG)

TIA

**Comment by synpc** [comment]
hi

have experimented with the following combinations preferences and params, with the results in the web client as indicated
- export as collada, generate with surface, appearance with texture
  - buildings render as grey blocks
- export as collada, not generate with surface, appearance with texture
  - buildings render as black blocks

apprec any hlp pls
thx

**Comment by Son-HNguyen** [comment]
Could you provide us an excerpt of your dataset for testing?

**Comment by synpc** [comment]
hi
dataset used is classified;
trying to replicate problem using RTG_Schulungskurs_2016;
noticed that the texture images therein is of file extension jpg, while my classified dataset is using tif - can this be the problem? does webclient accept such files, or must be in jpg?
thnx again

**Comment by synpc** [comment]
hi
converted tif image to jpg;
import to fresh database
export with generated surface normal and texture
CAN now view textured facade in webclient
will close issue 
thnx again

**Comment by thomashkolbe** [comment]
Hi, yes this is very likely the problem. I would suggest
to convert the .tif texture images to .jpg and to replace
them in your dataset. For the conversion there are
a couple of Open Source tools that can convert.a folder
of .tif files into .jpg. Finally, the CityGML file(s) need 
to be updated. One possibility would be to do this
directly in the 3DCityDB and update all tuples in the 
respective table (I don‘t know the table name, but should
be easily identifiable from the documentation). Another
option would be to send the CityGML files through some 
line processor tool like „awk“ and to then search for
strings like .tif“ and to replace them with .jpg“ (I have 
included a quotation mark to reduce the risk that some
other string which might accidentially include .tif would
be replaced.

If you know how to do shell programming you could also 
try to replace the collada2gltf binary software by a shell
script with the same name, which then first checks if the
input image is of type .tif and in this case calls an
image conversion tool first and then feeds the generated
jpg file to the original collada2gltf binary software tool.

Best regards
Thomas Kolbe

---------------------------------------------
Prof. Dr. Thomas H. Kolbe
Chair of Geoinformatics
Institute for Geodesy, Geoinformatics, 
              and Land Management
Technische Universität München
Arcisstr. 21
81375 München, Germany
Tel. +49 89 28923888

**Comment by synpc** [comment]
hi
thnx for suggestions;
yes, did not prevly report this step, but i did have to manually find all the references in the raw gml pointing to the tif and change to jpg
then import into database
i suppose this is a learning point: documentation did not explicitly specify acceptable image format
thx/rgds
