### ISSUE TITLE
Migration of WebClient projects using GoogleFusionTables

### ISSUE THREAD

**Issue by BWibo** [3dcitydb/3dcitydb-web-map#45]
On December 3, 2019, Google Fusion Tables is being shut down, as announced [here](https://gsuiteupdates.googleblog.com/2018/12/google-fusion-tables-to-be-shut-down-on.html).

In the past, I've been using GoogleFusionTables a lot for providing thematic data for web client projects. Due to the shutdown, this data needs to be migrated to another service.
Google provides the [Fusion Tables Archive Tool](https://fusiontables-archive.withgoogle.com/) to copy existing tables to GoogleSpreadsheets or CSV (if Spreadsheet row limit of 5 Mio. rows is exceeded). This makes it easy to create a backup of your data and should be done anyway.

However, both GoogleSpreadsheet and CSV are currently not supported by the 3D Web Client.

How can thematic data be provided to the 3D web client in the future?

**Comment by Son-HNguyen** [comment]
We are aware of Google Fusion Tables being shut down. We are currently working on some alternatives and hope to be able to release a solution soon (and before December 3, 2019). Until then, it is recommended to backup your data if they were stored using Google Fusion Tables. Stay tuned for our updates!

**Comment by Son-HNguyen** [comment]
Added support for other thematic data sources such as Google Spreadsheets and PostgreSQL, see [release v1.8.1](https://github.com/3dcitydb/3dcitydb-web-map/releases/tag/v1.8.1).
