### ISSUE TITLE
GLTF renders on localhost but not on remote server

### ISSUE THREAD

**Issue by Itsman-AT** [3dcitydb/3dcitydb-web-map#46]
I have the problem, that my 3DCityDB created GLTF tiles load fine on localhost:

![grafik](https://user-images.githubusercontent.com/41750112/66493445-615dde80-eab6-11e9-8709-36ea682823e9.png)

but when I transfer the files to the production server I do not get the 3D representation, instead I seem to see the footprints only:

![grafik](https://user-images.githubusercontent.com/41750112/66493606-a3872000-eab6-11e9-84e4-5daef773db63.png)

Any hint what could be the problem? Logs show a lot of errors like this:

![grafik](https://user-images.githubusercontent.com/41750112/66493709-d03b3780-eab6-11e9-8262-133ddd662f3e.png)

**Comment by Itsman-AT** [comment]
Thanks for the swift reply @Son-HNguyen . Do partially non-existing GLB files keep the application from rendering at all? It seems, that only some of them are missing in the Tiles directories. I will investigate on this. Thanks again.

**Comment by Son-HNguyen** [comment]
Closed due to inactivity.
