### ISSUE TITLE
Querying 3D tiles

### ISSUE THREAD

**Issue by gioagu** [3dcitydb/3dcitydb-web-map#48]
Hi!

this is not necessary an issue, but rather a info request.

When uploading a 3D Tile in the 3DCityDB web viewer (1.8.2), you can select a feature, however no info is shown. I can (could) indeed store some simple attributes in the 3D Tiles (or at least the gmlid), but the this is not retrieved upon selecting/clicking on the object. 

Has the gmlid to be called in another way?
Is this the expected behaviour - at least for now?

Best regards

GA

**Comment by Son-HNguyen** [comment]
Hi!

If the thematic information is stored in a Google Spreadsheet or a PostgreSQL table, the 3DCityDB Web Map Client starting from v1.8.1 should be able to retrieve and display thematic data (as long as the objects in 3D tiles have IDs and these IDs match those in the thematic table; if you click on an object and no infobox is shown, then the clicked object does not have an ID). See the [release note](https://github.com/3dcitydb/3dcitydb-web-map/releases/tag/v1.8.1) for more information.

If you'd like to extract and display the thematic information stored within the 3D tiles themselves, then we haven't implemented this in the web client yet. It is an interesting feature though. We will have a look at it in a future release. Added to the enhancement list. :-)

Best,
Son

**Comment by gioagu** [comment]
Dear Son,

thanks for the quick reply.

Regarding PostgreSQL, yes, that was clear. I am planning to test/use it in the coming days.

Regarding 3D Tiles, this is exactly what I wanted to know. Looking forward to it! 
I guess you will have to specify how to name the id attribute to store in the 3D Tiles ('id", "gmlid", etc.). I guess the procedure to retrieve attributes from PostgreSQL should be the same then. For simmetry, I'd vote for "gmlid" :-)

Best regards,

GA

**Comment by Son-HNguyen** [comment]
Addressed in [v1.9.0](https://github.com/3dcitydb/3dcitydb-web-map/releases/tag/v1.9.0). This version supports display of thematic data of Cesium 3D Tiles.
