### ISSUE TITLE
Converting and using glb files (instead of gltf)

### ISSUE THREAD

**Issue by gioagu** [3dcitydb/3dcitydb-web-map#49]
As this is only mentioned rather quickly in the (current) Documentation, I was wondering whether you can share some experiences when converting (and using) glb files instead of gltf. Is a simple conversion of the gltf generated by the Importer/Exporter enough, or are some other tweaks necessary in viewer?

So far, I have had no success using the Collada2Gltf (version 2.15) to convert Collada to glb. I generate to glb, but I cannot visualise them correctly in the viewer. But I haven't tried (yet) other conversion tools directly from gltf to glb.

If you (or someone else) is willing to share some experience gathered so far, you are welcome! :-)

Best regards,

GA

**Comment by Son-HNguyen** [comment]
Hi!

To convert from COLLADA `.dae` to `.gltf` and `.glb` we used the tool [COLLADA2glTF](https://github.com/KhronosGroup/COLLADA2GLTF/) like you mentioned. I have not used a CLI/automated tool that converts `.gltf` to `.glb` but there seems to be some such as [this one](https://github.com/TimvanScherpenzeel/gltf-to-glb) (note that I have not tested this yet). Even so, the current web map client does not support `.glb` files. The implementation accepts files such as `.gltf` or `.kml` etc.

Best,
Son

**Comment by Son-HNguyen** [comment]
In case you still wish to have `.glb` file and are interested in "hacking" ;-) here is a quick how-to:

1. Clone the repository Importer/Exporter on your machine:
```
git clone https://github.com/3dcitydb/importer-exporter
```

2. Go to [this line](https://github.com/3dcitydb/importer-exporter/blob/master/impexp-kml-collada-plugin/src/main/java/org/citydb/modules/kml/database/KmlExporterManager.java#L657) in the source code and change it to this (mind the `"-b", "true"` added at the end for export of binary `.glb`)
```
ProcessBuilder pb = new ProcessBuilder(collada2gltfFile.getAbsolutePath(), "-i", colladaBundle.getGmlId() + ".dae", "-o", gltfModelFile.getAbsolutePath(), "-v", exportGltfV1 ? "1.0" : "2.0", "-b", "true");
```

3. Rebuild the project using Gradle and you should see exported files in `.glb` in place of `.gltf` now.

**Comment by gioagu** [comment]
Dear Son,

thanks for the reply. I think the point is that the current version of the web client does not support glb "out of the box", as you write. Thanks for clarifying it.

In the meanwhile, I was successful in using both COLLADA2glTF and gltf-pipeline (https://github.com/AnalyticalGraphicsInc/gltf-pipeline).

GA

**Comment by thomashkolbe** [comment]
Hi Son, 

I have read that CesiumJS supports loading `.glb` files directly (as an alternative to `.gltf`). Shouldn't it be easy to modify the KML/COLLADA/glTF exporter in such a way that it generates `.glb` files using your command line options shown above and then to include in the KML files references to the corresponding `.glb` files instead of `.gltf` (just change the file name suffixes)? This should not require any change to the 3D Webmap Client.

Furthermore, both CesiumJS and the COLLADA2GLTF tool support the Draco compression method which significantly compresses geometry data. I think you should also give it a try.

If `.glb` support works, please include a new switch in the GUI of the KML/COLLADA/glTF exporter. Hence, users could select whether they want to use binary encoded glTF. If Draco compression also works, please include another corresponding switch.

Best regards
Thomas

**Comment by Son-HNguyen** [comment]
Dear Thomas,

I already added the support for `.glb` and the corresponding switch in the GUI to the enhancement list before I replied to @gioagu . This is definitely a nice feature to have. Only slightly small problem currently is that the extension `.gltf` seems to be hardcoded at some places in the code and a general support for both `.gltf` and `.glb` might require some code refactoring as well as thorough testing. I was unsure if this can be done quicly so I wanted to investigate more on the code before announcing the fix/extension in the reply above.

I also added Draco compression to the enhancement list like you mentioned.

Best,
Son

**Comment by thomashkolbe** [comment]
Dear Son,

great! At least the places where the extension `.gltf` is being used should be easily findable by a simple search through all the source files. But I assume that you already considered this. I agree that these modifications will require some throrough testing.

Best regards
Thomas

**Comment by clausnagel** [comment]
We are always looking for contribution. @gioagu, maybe you want to join the work on this issue?

**Comment by Son-HNguyen** [comment]
Added support for `.glb` files besides `.gltf`. The web client is now able to automatically detect and visualize both `.gltf` and `.glb` files, see https://github.com/3dcitydb/3dcitydb-web-map/commit/737b4a017af5a0433c08df4d2e593a1e61152446.
