### ISSUE TITLE
Pagespeed

### ISSUE THREAD

**Issue by walterogrady** [3dcitydb/3dcitydb-web-map#5]
This is **problem and a solution** but there might be a better way to fix it permanently in the source code.

The CitydbUtil.js function `retrieveURL` uses the location of other script files to get the script's base url.
For example if a script is defined as:

```
<script src="/some/url/js/CitydbKmlHighlightingManager.js"></script>
```

then the `retrieveURL` returns `/some/url/js/`.

The problem is when [Pagespeed](https://developers.google.com/speed/pagespeed/module/) is used by the web host for optimisation. Pagespeed can 'optimise' this:

```
<script src="/newtrend/static/cesium/js/CitydbWebworker.js"></script>
<script src="/newtrend/static/cesium/js/CitydbSceneTransforms.js"></script>
<script src="/newtrend/static/cesium/js/CitydbKmlHighlightingManager.js"></script>   
<script src="/newtrend/static/cesium/js/CitydbKmlTilingManager.js"></script>
```

into

`<script src="/newtrend/static/cesium/js/CitydbWebworker.js+CitydbSceneTransforms.js+CitydbKmlHighlightingManager.js+CitydbKmlTilingManager.js.pagespeed.jc.oPQAHrW-xj.js"></script>`

and `retrieveURL` does not work with that.

A solution for an Apache web host is to add this

```
ModPagespeedDisallow "*/CitydbKmlHighlightingManager.js"
ModPagespeedDisallow "*/CitydbKmlTilingManager.js"
```

to the pagespeed.conf file. Or this:

```
<IfModule pagespeed_module>
    ModPagespeedDisallow "*/CitydbKmlHighlightingManager.js"
    ModPagespeedDisallow "*/CitydbKmlTilingManager.js"
</IfModule>
```

to the httpd.conf file. Then pagespeed leaves the script declaration as is. There are other formats for other host types.

I hope this helps.

**Comment by yaozhihang** [comment]
Thank you very much for this comment. You are right, in the future release, the source code of our 3D web client should be optimized to handle this issue .
