### ISSUE TITLE
PostgreSQL API response documentation

### ISSUE THREAD

**Issue by mulfvik** [3dcitydb/3dcitydb-web-map#51]
Hi,
I already have an API for quering data from PostgreSQL that I want to use for the `thematicDataSource `. The json response from API looks like this at the moment
`{"gmlid":"UUID_BYGGNAD_1a7dbc23-63f9-4e1c-be52-2bc4fb8e1150","fastighetsnyckel":"040096351"}` and the client loggs in console
`Map(0) {}
[[Entries]]
No properties
size: (...)`
So my question is how the API respons should look like for the client to accept and render it in the info box? Should it be json?
Thank you!
I would be happy to help out with documentation bit when this is solved.

**Comment by mulfvik** [comment]
So, enclosing the json response object in an array solved this issue in "Horizontal" mode, response example:
`[{gmlid: "UUID_BYGGNAD_1a7dbc23-63f9-4e1c-be52-2bc4fb8e1150", fastighetsnyckel: "040096351"}]`

**Comment by Son-HNguyen** [comment]
Hi,

I was writing and saw you've already solved it! :)

Yes, both the horizontal and vertical mode consist of an array of records marked by the `[ ... ]`. Each record represents a line in the table, where:

+ Each record in vertical mode only has exactly 3 elements: `gmlid`, attribute name and attribute value. The `gmlids` here can be duplicated in other records, but the combination of these 3 elements must be unique.
   ```
   [
      { gmlid : "id1", value_name : "value" },
      {gmlid:"id2", value_name : "value" },
      ...
   ]
   ```

+ On the other hand, each record in the horizontal mode can have more than 2 elements, but the first one must always be `gmlid` and this must be unique for each record.

**Comment by Son-HNguyen** [comment]
I've updated the [change logs](https://github.com/3dcitydb/3dcitydb-web-map/blob/master/CHANGES.md#important-changes) and [release notes](https://github.com/3dcitydb/3dcitydb-web-map/releases/tag/v1.8.1) to include some explanation about the structure of the JSON responses accepted by the web client. 

You are more than welcome to contribute to extending the change logs above or our online documentation [here](https://3dcitydb-docs.readthedocs.io/en/latest/index.html) and [here](https://github.com/3dcitydb/3dcitydb-docs). Just make a pull request and we will be able to review your changes.

Best regards,
Son
