### ISSUE TITLE
ThematicData on object

### ISSUE THREAD

**Issue by AkiTuomaala** [3dcitydb/3dcitydb-web-map#54]
Hi!

I've been struggling to get data seen in cesium while using PostgREST:

My Building object
![image](https://user-images.githubusercontent.com/64587318/81807553-f9c5b100-9526-11ea-82de-3ff86ce274eb.png)

My PostgREST result
![image](https://user-images.githubusercontent.com/64587318/81807613-119d3500-9527-11ea-9099-36d32a156a00.png)

Layer details in Cesium:
URL -> localhost:8000/buildings_collada_master.json
ThematicDataUrl -> http://localhost:3000/api_building
CityObjectsJsonUrl -> localhost:8000/buildings.json

Anyone had similar problems with PostgREST?

**Comment by Son-HNguyen** [comment]
What type of tables (vertical/horizontal) did you select in the web client?

**Comment by AkiTuomaala** [comment]
Hi @Son-HNguyen!

Im not sure what you mean by "select", but I went with this "3 element idea"
![image](https://user-images.githubusercontent.com/64587318/81857944-a3c72c80-956b-11ea-9511-e65e278d9684.png)

So if im getting right, its suppose to be vertical type of tables.

**Comment by Son-HNguyen** [comment]
Make sure you select this option in the main toolbox:
![image](https://user-images.githubusercontent.com/5765503/81858483-1d5b1c80-9564-11ea-83bd-c976e2553b18.png)

The table type `One row per object attribute` is for vertical tables.

**Comment by AkiTuomaala** [comment]
Ah..
I didnt check at all what version I had from 3dcitydb-web-map... Downloaded "Importer_Exporter_4.2.3" and was using version what they had in there...
Will try out with new version.. Thank you in front @Son-HNguyen!

**Comment by AkiTuomaala** [comment]
Installed newest version and now it works like a charm!
Thank you again!

**Comment by Son-HNguyen** [comment]
Glad it helped! :)
