### ISSUE TITLE
Loading Cesium 3D tiles broken?

### ISSUE THREAD

**Issue by gioagu** [3dcitydb/3dcitydb-web-map#55]
Hi!

I am wondering whether the Cesium 3D tiles support is broken, or I am doing something wrong. 
In the current version (1.8.3) I get an error message (Failed to load ....)
The same _exact_ tileset can be loaded and visualised using version 1.8.0 (I have both versions of the 3DcityDB-web-map running and sharing the same data source).

I add for simple testing a zipped version of the dataset.

BR

[tileset.zip](https://github.com/3dcitydb/3dcitydb-web-map/files/4649547/tileset.zip)

**Comment by Son-HNguyen** [comment]
Thanks for the bug report. I fixed it  in https://github.com/3dcitydb/3dcitydb-web-map/commit/9966228394acc86c51578e40e322c9c699617e6a.
