### ISSUE TITLE
Bounding Box

### ISSUE THREAD

**Issue by walterogrady** [3dcitydb/3dcitydb-web-map#6]
Is there a way to access the bounding box and edit it's properties (e.g. colour)?

**Comment by yaozhihang** [comment]
check this:
https://github.com/3dcitydb/3dcitydb-web-map/blob/master/js/CitydbKmlTilingManager.js#L419

**Comment by walterogrady** [comment]
That's what I changed. I was wondering if the properties were editable without altering the script file code.

**Comment by yaozhihang** [comment]
No, the only way for that is to adpat the source code.

**Comment by lucasvw** [comment]
Hi Walter,

This is Lucas. Richard and I gave you a training a while back at virtualcitysystems.

How is it going? Good to be reading you guys are working with the 3d-city web map! What are you building? Already something to look at? ;)

Here is something that might be handy:
```
CitydbKmlTilingManager.prototype.createBboxGeometry = function(bbox, opt_color) {
        opt_color = opt_color || Cesium.Color.BLUE
    	var rectangle = Cesium.Rectangle.fromDegrees(bbox.xmin, bbox.ymin, bbox.xmax, bbox.ymax);
    	var cesiumViewer = this.citydbKmlLayerInstance.cesiumViewer;
    	this.boundingboxEntity = {
        	id: Cesium.createGuid(),
            rectangle : {
                coordinates : rectangle,
                fill : false,
                outline : true,
                outlineWidth : 20,
                outlineColor : opt_color
            }
        }
        cesiumViewer.entities.add(this.boundingboxEntity);
    },
```
