### ISSUE TITLE
Questions on knockoutjs libraries used

### ISSUE THREAD

**Issue by eumora10** [3dcitydb/3dcitydb-web-map#63]
Hi,

Would like to check whether knockoutjs upgrade is in the pipeline for cesium.js used in 3dcitydb-web-map?
I am asking because there is some vulnerabilities reported: 
https://ossindex.sonatype.org/component/pkg:npm/knockout@3.4.2

Thank you.

**Comment by Son-HNguyen** [comment]
Hi, thanks for heads up. Cesium version 1.67.0 and newer seem to have updated knockout to 3.5.1. These will be considered by the next update of the CesiumJS library in this project.
