### ISSUE TITLE
PostgREST API structure documentation

### ISSUE THREAD

**Issue by elias-greve** [3dcitydb/3dcitydb-web-map#64]
This is a little feedback concerning the documentation of the PostgREST API thematic data source. 

In the documentation is written how the data structure should look like for the "One row per object attribute" option. 
In the "Note" section it is described correctly. 
```
[
   { gmlid : "id1", value_name : "value_name", value : "value" },
   { gmlid : "id2", value_name : "value_name", value : "value" },
   ...
]
```
When I create my VIEW in the db, I m getting the following result in the web viewer: 
![image](https://user-images.githubusercontent.com/86779268/124114955-830eae80-da6d-11eb-8323-03eb37ddf27e.png)
while the PostgREST response is the following: 
```
[{"gmlid":"DENW47AL10007dpx","value_name":"DatenquelleDachhoehe","value":"1500"}, 
 {"gmlid":"DENW47AL10007dpx","value_name":"Gemeindeschluessel","value":"05512000"}, 
 {"gmlid":"DENW47AL10007dpx","value_name":"DatenquelleBodenhoehe","value":"11001"}, 
 {"gmlid":"DENW47AL10007dpx","value_name":"DatenquelleLage","value":"10001"}]
```

Which looks like in the documentation described, but somehow the web viewer can't identify the "value_name". 
By naming the column of the value_name into "attribute", the web viewer will display all values correctly. 

```
[{"gmlid":"DENW47AL10007dpx","attribute":"DatenquelleDachhoehe","value":"1500"}, 
 {"gmlid":"DENW47AL10007dpx","attribute":"Gemeindeschluessel","value":"05512000"}, 
 {"gmlid":"DENW47AL10007dpx","attribute":"DatenquelleBodenhoehe","value":"11001"}, 
 {"gmlid":"DENW47AL10007dpx","attribute":"DatenquelleLage","value":"10001"}]
```
![image](https://user-images.githubusercontent.com/86779268/124115416-10ea9980-da6e-11eb-96f1-da03003e7cd8.png)

Maybe you could update the data structure in a way that the identifier for the attribute name should be "attribute" instead of "value_name". 
```
[
   { gmlid : "id1", attribute : "value_name", value : "value" },
   { gmlid : "id2", attribute : "value_name", value : "value" },
   ...
]
```

Another remark at this point: The PostgREST API response has quotes around the column names as shown in my PostgREST responses. At first I thought that this would maybe my fault and I have to get rid of the quotes in the PostgREST response.

**Comment by Son-HNguyen** [comment]
Hi @elias-greve, thank you for the heads up! The column name is indeed mentioned inconsistently between the documentation and the implementation. The correct one should be, like you already mentioned, `attribute`, and NOT `value_name`. You are also right with the quotes in the PostgREST response, they need to be there:
 ```
 [
    { "gmlid" : "id1", "attribute" : "value_name", "value" : "value" },
    { "gmlid" : "id2", "attribute" : "value_name", "value" : "value" },
    ...
 ]
 ```

Note that this does not affect the implementation, only the documentation had some inconsistencies.

I've updated the documentation accordingly, see:
https://github.com/3dcitydb/3dcitydb-web-map/blob/master/CHANGES.md
https://3dcitydb-docs.readthedocs.io/en/latest/webmap/online-spreadsheet.html
https://github.com/3dcitydb/3dcitydb-web-map/releases/tag/v1.9.0
