### ISSUE TITLE
GMLID not exist on database table

### ISSUE THREAD

**Issue by ozaapt** [3dcitydb/3dcitydb-web-map#66]
![image](https://user-images.githubusercontent.com/87305472/125269386-d832a600-e332-11eb-9362-df3892bca808.png)

i successfully import and export my 3D file. i want to try show atribut on window using posgres API. atribute not show. 
then i investigate this issue, evidently GMLID not exist on database.

![image](https://user-images.githubusercontent.com/87305472/125269356-cd781100-e332-11eb-9e7a-ca87917b1a2d.png)

![image](https://user-images.githubusercontent.com/87305472/125269058-8be76600-e332-11eb-83be-5f9cac3fdc79.png)

How did this happen? any error or fail step ?

**Comment by Son-HNguyen** [comment]
Try querying the GMLIDs in the building table if see if they can be found there. You can use VIEWs to extract or combine information that you'd like to publish via PostgREST.

**Comment by ozaapt** [comment]
thanks for your advice, i found my gmlid on other table
