### ISSUE TITLE
Cannot GET /3dcitydb-web-map/3dwebclient/index.html 

### ISSUE THREAD

**Issue by kauevestena** [3dcitydb/3dcitydb-web-map#67]
I tried to execute the server following the instructions, from:

https://3dcitydb-docs.readthedocs.io/en/release-v4.2.3/webmap/installation-config.html 

And it only shows

    Cannot GET /3dcitydb-web-map/3dwebclient/index.html 

What can it be?

**Comment by Son-HNguyen** [comment]
I assume you used the command 
```bash
node server.js
```
to run the client? What are the errors displayed on the console while you were running NodeJS?

**Comment by kauevestena** [comment]
I was using an outdated version of the documentation, the address has been updated...

at http://localhost:8000/3dwebclient/index.html its working very fine

sorry for my lack of knowledge

**Comment by Son-HNguyen** [comment]
Hi @kauevestena, I'm glad it worked out. No worries, we are here to help and your question may be very useful for others as well. The latest documentation can be found using the following URL:
https://3dcitydb-docs.readthedocs.io/en/latest/webmap/installation-config.html
