### ISSUE TITLE
Visualization of KML file exported by ImpExp without the json files

### ISSUE THREAD

**Issue by lisha992610** [3dcitydb/3dcitydb-web-map#68]
Hi. 

I am working on the visualization by using 3dcitydb-web-map-client. Previously I have successfully exported the data in KML format with extruded display form (simple envelop) using the importer-exporter tool. It has been result in a single file (using single object option) which can be visualized in Cesium ion and Google earth. No json file has been generated even though the preference option of "write the json" is checked. 

Further I would like to use the 3dcitydb-web-map-client to visualize the generated KML file, but it seems that the masterjson file and json for the tiles are required. Is it correct? and only the bounding box option of the importer-exporter will generate the both json file. 

Is it possible to use the web-map-client to visualize a single KML file without the json files? Thank you.

**Comment by Son-HNguyen** [comment]
Hi, normally a master JSON file exported from the Importer/Exporter is required to add a KML/COLLADA/glTF layer to the web client. Export for extruded should also contain a master JSON file if the option to write a JSON master file is also enabled in the preferences. I've just tested it with both the Importer/Exporter version 4.2.3 and 4.3.0 and it works. Please use the latest Importer/Exporter and if the master JSON is still not exported despite the enabled option, please report it in https://github.com/3dcitydb/importer-exporter/issues.
