### ISSUE TITLE
Editing capabillity?

### ISSUE THREAD

**Issue by Abelon38** [3dcitydb/3dcitydb-web-map#7]
Hi Guys! 
First of all thank you for the great work you have done and shared!
I work at Nackas Municipality in Sweden and we are looking for a 3D software where we could freely show our 3D data and construction plans for the public. The main idea is that the public will be able to register their comments on the map-web by inserting an icon etc. 
Is there a plugin or module that permits to archive this? 

Thank you for your time!
Abel Gonzalez

**Comment by yaozhihang** [comment]
Hi Abel,

thanks for your kind comment on our work.

Actually, a number of enhanced versions of the 3d-web-map-client have been developed within the framework of research projects carried out in our department (Char of Geoinformatics at Technical University of Munich). In these versions, some of the functionalities you mentioned like Editing capability, collaborative creation of icon with user comments etc. have already been implemented. These functionalities might be added to the open source version of the 3d-web-map-client in its future release.

Regards,

Zhihang

**Comment by Abelon38** [comment]
Thank you a lot for your answer and time! I will start using 3dcitydb web
map in our organization.
Is there a way i could contribute to this project?
Regards,
Abel

Den 8 nov. 2016 10:24 em skrev "Zhihang Yao" <notifications@github.com>:

**Comment by yaozhihang** [comment]
Yes, if you would like to contribute code for adding new features or for fixing issues, simply fork our repositories and make your pull requests.

**Comment by Abelon38** [comment]
Hi Zhihang !

Do you know where to download the 3D web client show on this link:
http://www.3dcitydb.net/3dcitydb/fileadmin/3DWebClient/index.html

Regards,
Abel gonzalez

2016-11-24 21:14 GMT+01:00 Zhihang Yao <notifications@github.com>:
