### ISSUE TITLE
Building and Room color

### ISSUE THREAD

**Issue by ozaapt** [3dcitydb/3dcitydb-web-map#70]
Hello, i want the building and room color show in 3dcitydb-web-map have same color with the building in gml file, is there any method to do that?

![WhatsApp Image 2021-09-09 at 17 07 07](https://user-images.githubusercontent.com/87305472/132676222-e517ad8a-73e7-4b45-b493-beaa603471c1.jpeg)
![image](https://user-images.githubusercontent.com/87305472/132676274-d5b8e690-f280-4618-bc28-fe33012245d9.png)

thank you.

**Comment by thomashkolbe** [comment]
When your objects have Appearance elements assigned in the CityGML file, you should choose to export them in COLLADA/glTF format. Be sure to connect to your database by fetching the available appearance themes and choosing the relevant one. This can all be done on the main tab of the visualization exporter. See [https://3dcitydb-docs.readthedocs.io/en/latest/impexp/export-vis.html](https://3dcitydb-docs.readthedocs.io/en/latest/impexp/export-vis.html)

However, this only works, when appearances have been assigned to the objects in the CityGML file and the appearance theme has not been left empty.

**Comment by ozaapt** [comment]
thank you.
