### ISSUE TITLE
Unable to visuliasze on 3D Web Map Client

### ISSUE THREAD

**Issue by Ferkelcode** [3dcitydb/3dcitydb-web-map#75]
Hello, 

I have got the MasterJSON as below: 

> {
> 	"version": "1.0.0",
> 	"layername": "kml01",
> 	"fileextension": ".kmz",
> 	"displayform": "extruded",
> 	"minLodPixels": 120,
> 	"maxLodPixels": -1,
> 	"colnum": 1,
> 	"rownum": 1,
> 	"bbox":{ 
> 		"xmin": 5.937952819198381,
> 		"xmax": 46.62039596564427,
> 		"ymin": 42.933776289335235,
> 		"ymax": 51.45619575225303
> 	}
> }
> 

And I have exported the xlsx file with a few columns according to the tutorial '3D City Database for CityGML A Hands-on Tutorial for Beginners Version 4.0.0':

Building_Height_Unit - BUILDING/MEASURED_HEIGHT_UNIT
Street_Name - ADDRESS/[FIRST]STREET
House_Number - ADDRESS/[FIRST]HOUSE_NUMBER
Denkmal_Art - CITYOBJECT_GENERICATTRIB/STRVAL[ATTRNAME='DENKMALART']

But I could not see any building in the web map.

Do you know what could be the problme? I don't know what columns are necessary in the spreadsheet. And also I didnt check the Tiling Filter when doing the VIS export. Could these be the problem?

**Comment by clausnagel** [comment]
Moved to `3dcitydb-web-map` repository

**Comment by Son-HNguyen** [comment]
Hi, could you please show the errors shown in the browser (in developer mode)? If you could not see any building, it might be another problem than your spreadsheet. Make sure that the exported files (glTF for example) are made available (at least for `localhost`) so you can use them in your browser.
