### ISSUE TITLE
wms not working?

### ISSUE THREAD

**Issue by Abelon38** [3dcitydb/3dcitydb-web-map#9]
Hi there!

I have tried to connect a WMS från owr QGIS server and Geoserver and din´t work. The whole globe turned blue. Is there something I am doing wrong? 
Thanks for your time!
Abel Gonzalez

**Comment by yaozhihang** [comment]
Hi Abel,

are you using the NodeJS-based web server delievered together with the 3dcitydb-web-map?
If not, you may need to set up a proxy for your client server or enable the CORS of the WMS-Server in order to overcome the cross-domain issue. For more details please refer to the 3DCityDB-Documentation-3.3 (chapter 8.3.3) 

Zhihang

**Comment by Abelon38** [comment]
Thank Zhihang!
I am using a tomcat. I will check the cors then.
Have a good weekend!
Abel

Den 18 nov. 2016 4:49 em skrev "Zhihang Yao" <notifications@github.com>:

**Comment by Abelon38** [comment]
Hi Zhihang!

I have tried with NodeJs server but I am geting this error: *Cannot GET / *
Do you have an idea of what could be wrong?

Thansk for your time!
Abel

2016-11-18 16:54 GMT+01:00 Abel Gonzalez <abel.gonzalez.c@gmail.com>:

**Comment by yaozhihang** [comment]
Hi Abel,

could you explain this issue in more detail? for example, which HTML request causes this error message?

regards,

Zhihang

**Comment by Abelon38** [comment]
Hi Zhihang!
I just did as it is explained in the documentation. I tasted on windows
server and on Windows 8 and i get the same error.
1.  Installed node js
2. Started via cmd the server.js
3. When pronted localhost:8000 i get "cannot GET"

Regards!
Abel

Den 21 nov. 2016 9:51 em skrev "Zhihang Yao" <notifications@github.com>:

**Comment by yaozhihang** [comment]
Hi Abel,

you need to use the URL "http://localhost:8000/3dwebclient/index.html" to launch the 3D web client.

best,

Zhihang

**Comment by Abelon38** [comment]
Hi! Yes i did it but i get the same error.
I will come back tomorrow with more datails.

Thank you a lot for your help and time!
Abel

Den 21 nov. 2016 10:40 em skrev "Zhihang Yao" <notifications@github.com>:

**Comment by Abelon38** [comment]
Hi Zhihang!

Now it is working well on NoderJS server. It started working after  Windows
restart.

Thank you for your time!
Regards
Abel

2016-11-21 22:44 GMT+01:00 Abel Gonzalez <abel.gonzalez.c@gmail.com>:
